# Generated by Django 2.0 on 2019-03-04 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KeyInfoExtract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('key_info', models.TextField()),
                ('time', models.TimeField()),
            ],
            options={
                'db_table': 'kie',
                'verbose_name': '关键信息抽取',
                'verbose_name_plural': '关键信息抽取',
            },
        ),
    ]
